// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_96r3aYykIr8i2ZrKTd9UzsqV-FjMK6g',
    appId: '1:1088642855812:web:82ca2bca73141e40ca63d1',
    messagingSenderId: '1088642855812',
    projectId: 'lua-cydeva',
    authDomain: 'lua-cydeva.firebaseapp.com',
    storageBucket: 'lua-cydeva.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDcgGfnXvesXiJd_TPS-8yjfm0Yiq8UsQ',
    appId: '1:1088642855812:android:e9bfa204d169359aca63d1',
    messagingSenderId: '1088642855812',
    projectId: 'lua-cydeva',
    storageBucket: 'lua-cydeva.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-sz40e1lpmygb1uQjqJA025JGnJJxGKI',
    appId: '1:1088642855812:ios:102592a378f17802ca63d1',
    messagingSenderId: '1088642855812',
    projectId: 'lua-cydeva',
    storageBucket: 'lua-cydeva.appspot.com',
    androidClientId: '1088642855812-0qkjomnqu1353sjg5s7itobi7oeihaeg.apps.googleusercontent.com',
    iosClientId: '1088642855812-aokeod3q233pkd0j0tmcvm9mbh9f3eri.apps.googleusercontent.com',
    iosBundleId: 'com.example.luaV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-sz40e1lpmygb1uQjqJA025JGnJJxGKI',
    appId: '1:1088642855812:ios:b8ae98e55095167bca63d1',
    messagingSenderId: '1088642855812',
    projectId: 'lua-cydeva',
    storageBucket: 'lua-cydeva.appspot.com',
    androidClientId: '1088642855812-0qkjomnqu1353sjg5s7itobi7oeihaeg.apps.googleusercontent.com',
    iosClientId: '1088642855812-1vfruieigcrgtmb5jm3je8medg1oe588.apps.googleusercontent.com',
    iosBundleId: 'com.example.luaV3.RunnerTests',
  );
}
